### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hyblocker** [MMMaellon/SmartObjectSync#1]
Would you be willing to specify a license? From what I can tell by looking at the repository, there isn't one specified at present.

**Comment by MMMaellon** [comment]
License is here: https://github.com/MMMaellon/SmartObjectSync/blob/main/Packages/com.mmmaellon.smartobjectsync/LICENSE
Different parts of this git repo are under different licenses because VRChat requires that you include the whole unity project, but all my code is MIT licensed
