### ISSUE TITLE
Synced objects randomly dissappear when using anything after 3.0.1

### ISSUE THREAD

**Issue by Piano-Walrus** [MMMaellon/SmartObjectSync#5]
So I've been waiting a bit to submit this because I wasn't sure if it was a me problem, or if you'd fix it in a future version. However, I've tried using multiple versions of SmartObjectSync (including the latest one) in my Udon Jenga world, and with any version after 3.0.1 (I don't remember if 3.0.2 works, but I can show private examples of any version you'd need me to test with my Jenga prefab, or anything else that might help identify the issue) most, or sometimes all of the blocks will just disappear after the player moves a bit away from spawn. A while back when I tried only implementing SmartObjectSync on some of the plushies in the world, they mysteriously disappeared once when toggled. That's when I decided to just settle for 3.0.1 for the time being. 

Again, I can show my setup or any examples or anything if needed, or we could schedule a quick second if you'd want me to upload a private test of any given version so you can test the behavior.

**Comment by MMMaellon** [comment]
Would love to see a private example because I have not encountered this at
all. I've also been using SmartObjectSync extensively in my own projects
with no issues.

Some questions:
1) How do you trigger the issue? Does it happen randomly?
2) Does it happen in client sim or only in game
3) Do you need a lot of people in the world for the issue to happen? And
does everyone see it disappear at once?

**Comment by MMMaellon** [comment]
btw you can reach me at @mmmaellon on Discord or my Twitter dms (https://x.com/MMMaellon)

**Comment by Piano-Walrus** [comment]
1. It seems fairly random, though it usually seems to happen once the player has finished spawning, and moves a bit out of the spawn area. However, that could just be a coincidental "it's a consistent timed event that just tends to happen after that amount of time has passed" so I'm not sure. 
2. I never use the ClientSim because it has never once behaved the way the game does, at least for me (most of what I test tends to be UI based, and ClientSim hates buttons, lol). However, it does happen when I do "Build and Test" if that helps, and I can try testing in the ClientSim soon once I'm back from vacation if needed.
3. No, it even happens when only one person is in the world. Also, I can't remember if they disappear for everyone, but I do remember them disappearing for a friend during a test once (though, again, I don't remember if they disappeared for me in that instance. Maybe they only disappear for owner? idk)

**Comment by MMMaellon** [comment]
We connected over discord and found that the issue was the way that objects respawn when using local space teleports. fix is in version 3.10.0
